// Code generated by "stringer -type=Severity"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VERBOSE-0]
	_ = x[DEBUG-1]
	_ = x[INFO-2]
	_ = x[WARN-3]
	_ = x[ERROR-4]
	_ = x[FATAL-5]
}

const _Severity_name = "VERBOSEDEBUGINFOWARNERRORFATAL"

var _Severity_index = [...]uint8{0, 7, 12, 16, 20, 25, 30}

func (i Severity) String() string {
	if i < 0 || i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
